name: Deploy Angular ApiUsers
on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18.17.1
          cache: "npm"
      - name: install dependencies
        run: npm install --no-audit --no-fund --omit=optional
      - name: eslint run
        run: ls -l
      - run: ls -a
      - run: cd /
      - run: ls -a
