name: Deploy Angular ApiUsers
on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-22.04.3
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18.17.1
          cache: "npm"
      - name: install dependencies
        run: npm install
